admin 
{
    naveenjanapati65@gmail.com ,
    jvn123
}

organizers [
    {
        charan@gmail.com
        charan123
    }
]
user [
    {
        kasarampremkumar@gmail.com
        prem123
    }
    {
        venkatanaveenkumarjanapati@gmail.com
        naveen123
    }
]