admin 
{
    naveenjanapati65@gmail.com ,
    jvn123
}

organizers [
    {
        charan@gmail.com
        charan123
    }
    {
        kalyankamisetty4@gmail.com,
        pk123
    }
    {
        ravikishorekantragunta@gmail.com
        bhai123
    }
]
user [

    {
        kasarampremkumar@gmail.com
        prem123
    }
    {
        venkatanaveenkumarjanapati@gmail.com
        naveen123
    }
    {
        jangalav58@gmail.com
        venky123
    }
    {
        sivatejagonaboina@gmail.com 
        siva123
    }
    {
        srinivasarao.com12@gmail.com
        srinu123
    }
    {
        madhukarnanda8@gmail.com
        madhu123
    }
]